apiVersion: v1
kind: Service
metadata:
  labels:
    id: bikepesquisaid
  name: bikepesquisa
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
    nodePort: 31514   
  selector:
    id: bikepesquisaid
  type: NodePort